exp: MinimalPair

mode:
    - train

models:
    hf_masked_model:
      - bert-base-multilingual-uncased

trainfpath: /home/esuritis/NLP/FINAL/Cross-lingual-LLM-gender-bias/biasedTranslations/bias-en.tsv
validfpath: /home/esuritis/NLP/FINAL/Cross-lingual-LLM-gender-bias/biasedTranslations/bias-en.tsv
modelfpath: /home/esuritis/NLP/FINAL/Cross-lingual-LLM-gender-bias/models/BIAS2

loadPretrained: True

epochs: 20
learning_rate: 0.0001