exp: MinimalPair

mode:
    - train

models:
    hf_masked_model:
      - /home/esuritis/NLP/FINAL/Cross-lingual-LLM-gender-bias/models/BIAS2

trainfpath: /home/esuritis/NLP/FINAL/Cross-lingual-LLM-gender-bias/unbiasedTranslations/unbias-nl.tsv
validfpath: /home/esuritis/NLP/FINAL/Cross-lingual-LLM-gender-bias/unbiasedTranslations/unbias-nl.tsv
modelfpath: /home/esuritis/NLP/FINAL/Cross-lingual-LLM-gender-bias/models/UnbiasNL2

loadPretrained: True

epochs: 20
learning_rate: 0.0001